export const typeEmpresaDepartamento = {
    SET_EMPRESA: "SET_EMPRESA",
    CHANGE_PROPERTY_EMPRESA: "CHANGE_PROPERTY_EMPRESA",
    SET_DEPARTAMENTO: "SET_DEPARTAMENTO",
    CHANGE_PROPERTY_DEPARTAMENTO: "CHANGE_PROPERTY_DEPARTAMENTO",
    CLEAR_STATE: "CLEAR_STATE"
} 

export default typeEmpresaDepartamento;