export const typeDispositivos = {
    SET_DISPOSITIVO: "SET_DISPOSITIVO",
    CHANGE_PROPERTY_DISPOSITIVO: "CHANGE_PROPERTY_DISPOSITIVO",
    SET_INFORMACION: "SET_INFORMACION",
    CHANGE_PROPERTY_INFORMACION: "CHANGE_PROPERTY_INFORMACION",
    CHANGE_USUARIO: "CHANGE_USUARIO",
    CLEAR_STATE: "CLEAR_STATE"
} 

export default typeDispositivos;