export const typeEquipos = {
    SET_EQUIPO: "SET_EQUIPO",
    CHANGE_PROPERTY_EQUIPO: "CHANGE_PROPERTY_EQUIPO",
    SET_INFORMACION: "SET_INFORMACION",
    CHANGE_PROPERTY_INFORMACION: "CHANGE_PROPERTY_INFORMACION",
    CHANGE_USUARIO: "CHANGE_USUARIO",
    CLEAR_STATE: "CLEAR_STATE"
} 

export default typeEquipos;