export const typeImpresoras = {
    SET_IMPRESORA: "SET_IMPRESORA",
    CHANGE_PROPERTY_IMPRESORA: "CHANGE_PROPERTY_IMPRESORA",
    SET_INFORMACION: "SET_INFORMACION",
    CHANGE_PROPERTY_INFORMACION: "CHANGE_PROPERTY_INFORMACION",
    CHANGE_USUARIO: "CHANGE_USUARIO",
    CLEAR_STATE: "CLEAR_STATE"
} 

export default typeImpresoras;